feat: change to uv

diff --git a/.github/workflows/true-love-ai.yml b/.github/workflows/true-love-ai.yml
--- a/.github/workflows/true-love-ai.yml
+++ b/.github/workflows/true-love-ai.yml
@@ -1,8 +1,11 @@
-name: Deploy to Server via SSH
+name: true-love-ai Deploy to ser1 via SSH
 
 on:
   push:
     branches: [ "master" ]
+    paths:
+      - "true-love-ai/**"
+      - ".github/workflows/true-love-ai.yml"
 
 env:
   SERVER_IP: ${{ secrets.PROXY_HOST }}
@@ -34,7 +37,29 @@ jobs:
           ssh -o StrictHostKeyChecking=no -p ${{ secrets.SER1_PROXY_PORT }} ${{ env.SERVER_USER }}@${{ env.SERVER_IP }} << 'EOF'
             cd /root/true-love-n/true-love-ai
             git pull
-            systemctl restart true-love-ai
+          
+            # 保证uv 安装
+            if ! command -v uv >/dev/null 2>&1; then
+                echo "uv not found, installing..."
+                curl -LsSf https://astral.sh/uv/install.sh | sh
+                if ! grep -q 'export PATH="$HOME/.local/bin:$PATH"' ~/.bashrc; then
+                    echo 'export PATH="$HOME/.local/bin:$PATH"' >> ~/.bashrc
+                fi
+                export PATH="$HOME/.local/bin:$PATH"
+            else
+                echo "uv already installed."
+            fi
+            uv sync --locked
+          
+            # 保证pm2 安装
+            if ! command -v pm2 >/dev/null 2>&1; then
+                echo "pm2 not found, installing..."
+                npm install -g pm2
+                pm2 startup systemd
+            else
+                echo "pm2 already installed."
+            fi
+            pm2 restart ecosystem.config.js --update-env && pm2 save
           EOF
 
       - name: Notify - ai Success
